--liquibase formatted sql

--changeset zhernovoy:04 labels: release1.0

CREATE TABLE USER_MODE(
    MODE VARCHAR(10) PRIMARY KEY
);

CREATE TABLE AVAILABLE_COMMAND(
    ID VARCHAR(10),
    MODE VARCHAR(10),
    CONSTRAINT COMMANDS PRIMARY KEY (ID, MODE)
);

