--liquibase formatted sql

--changeset zhernovoy:02 labels: release1.0

CREATE TABLE COMMAND(
    ID VARCHAR(10) PRIMARY KEY
);

CREATE TABLE COMMAND_TEXT(
    ID VARCHAR(10) PRIMARY KEY,
    LANG VARCHAR(2),
    TEXT VARCHAR(30)
);

ALTER  TABLE  COMMAND
    ADD  CONSTRAINT  FK_COMMAND
    FOREIGN  KEY  (ID)
    REFERENCES  COMMAND_TEXT  (ID)
    ON  UPDATE  RESTRICT  ON  DELETE  CASCADE  DEFERRABLE  INITIALLY  DEFERRED;